import Head from 'next/head'
import HeaderComponent from '../components/Homepage/header-component'
import stylesHp from '../styles/Homepage/Homepage.module.css';
import { getHomepageById} from "../lib/Homepage/homepage-lib";
import Homepage from "../types/Homepage/homepage-type";
import FooterComponent from '../components/Homepage/footer-component';
import { HOMEPAGE_ID } from '../lib/Common/constants';
import { Carousel } from '../components/Carousel';

export async function getStaticProps({ preview = false}){
  const homepage = await getHomepageById(HOMEPAGE_ID);
  return{
      props: { homepage, preview},
      // Next.js will attempt to re-generate the page:
      // - When a request comes in
      // - At most once every 10 seconds
      revalidate: 10, //in seconds
  }
  
}

type Props = {
  homepage: Homepage;
}

const Homepage = ({homepage}: Props) => {

  return (
    <div className={stylesHp.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <main className={stylesHp.main}>
        <HeaderComponent  allHeaders={homepage.header} />
        <div className={stylesHp.content} style={{backgroundImage: `url("${homepage?.background?.results?.[0]?.fileUrl}")`}}>
          <Carousel articles={homepage.articles} />
        </div>

        <FooterComponent allFooters={homepage.footer} />
      </main>
    </div>
  )
}
export default Homepage;
